config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users, only: [:new, :create, :show] do
    resources :gymvisits, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :gymvisits, only: [:edit, :update, :destroy]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


end

app/models/gymvisit.rb
class Gymvisit < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :gymvisits

  validates :name, presence: true
  validates :password_digest, presence: true
  validates :email, presence: true, uniqueness: true

  enum role: %w(default admin)

  def update_total_points(redeemable_points)
    new_points = redeemable_points.to_i - self.total_points
    self.total_points = self.total_points + new_points
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/gymvisits_controller.rb
class Admin::GymvisitsController < Admin::BaseController

  def edit
    @gymvisit = Gymvisit.find(params[:id])
    @user = @gymvisit.user
  end

  def update
    @gymvisit = Gymvisit.find(params[:id])
    @gymvisit.update(gymvisit_params)
    redirect_to admin_user_path(@gymvisit.user)
  end

  def destroy
    @gymvisit = Gymvisit.find(params[:id])
    @gymvisit.destroy
    redirect_to admin_user_path(@gymvisit.user)
  end

  private

  def gymvisit_params
    params.require(:gymvisit).permit(:date, :calories_burned)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @gymvisits = @user.gymvisits
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_total_points(user_params[:redeemable_points])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:redeemable_points)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/gymvisits_controller.rb
class GymvisitsController < ApplicationController
  before_action :set_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @gymvisit = @user.gymvisits.new
  end

  def create
    @gymvisit = @user.gymvisits.create(gymvisit_params)
    redirect_to @user
  end

  def edit
    @gymvisit = @user.gymvisits.find(params[:id])
  end

  def update
    @gymvisit = Gymvisit.find(params[:id])
    @gymvisit.update_attributes(gymvisit_params)
    redirect_to @user
  end

  def destroy
    @gymvisit = Gymvisit.find(params[:id])
    @gymvisit.destroy
    redirect_to @user
  end

  private

  def gymvisit_params
    params.require(:gymvisit).permit(:date, :calories_burned)
  end

  def set_user
    @user = current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if @user.admin?
        redirect_to admin_users_path
      else
        redirect_to @user
      end
    else
      flash.now[:error] = "Invalid email or password."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Account created!"
      redirect_to @user
    else
      flash.now[:error] = "Your email or password is incorrect."
      render :new
    end
  end

  def show
    @user = current_user
    @gymvisits = @user.gymvisits
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/gymvisits/edit.html.erb
<h1>Admin Access</h1>


<h2>Edit <%= @user.name %>'s visit</h2>

<%= form_for(@gymvisit, url: admin_gymvisit_path(@gymvisit)) do |f| %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :calories_burned %>
  <%= f.text_field :calories_burned %>

  <%= f.submit "Update Visit" %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Assign Points for <%= @user.name %>:</h1>

<%= form_for(@user, url: admin_user_path(@user)) do |f| %>
  <%= f.label :redeemable_points %>
  <%= f.text_field :redeemable_points %>

  <!-- <%= f.label :total_points %>
  <%= f.text_field :total_points %> -->

  <%= f.submit "Submit Points" %>
<% end %>

app/views/admin/users/index.html.erb
<h1>Current Clients:</h1>

<ul>
  <% @users.each do |user| %>
    <% unless user.admin? %>
      <li>
        <%= link_to user.name, admin_user_path(user) %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/admin/users/show.html.erb
<h1>Admin Access</h1>
<h2><%= @user.name %></h2>

<div>
  <%= link_to "Assign Points", edit_admin_user_path(@user) %>
</div>

<div class="points">
  <p>Total Points: <%= @user.total_points %></p>
  <p>Redeemable Points: <%= @user.redeemable_points %></p>
  <p>Used Points: <%= @user.used_points %></p>
</div>

<div>
  <ul>
    <% @gymvisits.each do |visit| %>
      <li>
        <%= "#{visit.date}: #{visit.calories_burned}" %>
        <%= link_to "Edit Visit", edit_admin_gymvisit_path(visit) %>
        <%= link_to "Delete Visit", admin_gymvisit_path(visit), method: :delete %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "Record New Visit", new_user_gymvisit_path(@user.id) %>

app/views/gymvisits/edit.html.erb
<h1>Edit your visit</h1>

<%= form_for([@user, @gymvisit]) do |f| %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :calories_burned %>
  <%= f.text_field :calories_burned %>

  <%= f.submit "Update Visit" %>
<% end %>

app/views/gymvisits/new.html.erb
<h1>Record Your Gym Visit:</h1>

<%= form_for([@user, @gymvisit]) do |f| %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :calories_burned %>
  <%= f.text_field :calories_burned %>

  <%= f.submit "Record Visit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisitJim</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash-#{type}" %>
  <% end %>

  <% if current_user %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Login", login_path %><br>
    <%= link_to "Create new Account", new_user_path %>
  <% end %>

  <% if current_admin? %>
    <%= link_to "Admin Dashboard", admin_users_path %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Create an Account:</h1>

<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div class="points">
  <p>Total Points: <%= @user.total_points %></p>
  <p>Redeemable Points: <%= @user.redeemable_points %></p>
  <p>Used Points: <%= @user.used_points %></p>   
</div>

<div>
  <ul>
    <% @gymvisits.each do |visit| %>
      <li>
        <%= "#{visit.date}: #{visit.calories_burned}" %>
        <%= link_to "Edit Visit", edit_user_gymvisit_path(@user, visit) %>
        <%= link_to "Delete Visit", user_gymvisit_path(@user, visit), method: :delete %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "Record New Visit", new_user_gymvisit_path(@user.id) %>